controller_m21:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m21
    joint_speed: 1.0
    motor:
        id: 21
        init: 667
        min: 345
        max: 838

controller_m22:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m22
    joint_speed: 1.0
    motor:
        id: 22
        init: 512
        min: 103
        max: 905

controller_m23:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m23
    joint_speed: 1.0
    motor:
        id: 23
        init: 512
        min: 113
        max: 906
