
controller_m11:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m11
    joint_speed: 1.0
    motor:
        id: 11
        init: 545
        min: 207
        max: 682

controller_m12:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m12
    joint_speed: 1.0
    motor:
        id: 12
        init: 577
        min: 214
        max: 939

controller_m13:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m13
    joint_speed: 1.0
    motor:
        id: 13
        init: 424
        min: 36
        max: 818

controller_m21:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m21
    joint_speed: 1.0
    motor:
        id: 21
        init: 512
        min: 345
        max: 838

controller_m22:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m22
    joint_speed: 1.0
    motor:
        id: 22
        init: 512
        min: 103
        max: 905

controller_m23:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m23
    joint_speed: 1.0
    motor:
        id: 23
        init: 512
        min: 113
        max: 906

controller_m31:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m31
    joint_speed: 1.0
    motor:
        id: 31
        init: 512
        min: 341
        max: 838

controller_m32:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m32
    joint_speed: 1.0
    motor:
        id: 32
        init: 512
        min: 153
        max: 874

controller_m33:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m33
    joint_speed: 1.0
    motor:
        id: 33
        init: 512
        min: 138
        max: 889

controller_m41:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m41
    joint_speed: 1.0
    motor:
        id: 41
        init: 512
        min: 190
        max: 649

controller_m42:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m42
    joint_speed: 1.0
    motor:
        id: 42
        init: 512
        min: 153
        max: 874

controller_m43:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint_m43
    joint_speed: 1.0
    motor:
        id: 43
        init: 512
        min: 122
        max: 906

