obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.217,-0.051], [0,-0.051], [-0.217,-0.051], [-0.217,0.051], [0,0.051,], [0.217,0.051]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

map_type: costmap
bservation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: pico_flexx_optical_frame, data_type: PointCloud2, topic: /pico_flexx/points, marking: true, clearing: true}

