obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.217,-0.051], [0,-0.051], [-0.217,-0.051], [-0.217,0.051], [0,0.051,], [0.217,0.051]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

map_type: costmap
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

