obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.217,-0.051], [0,-0.051], [-0.217,-0.051], [-0.217,0.051], [0,0.051,], [0.217,0.051]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

plugins:
  - {name: static_layer1, type: "costmap_2d:: StaticLayer"}
  - {name: static_layer2, type: "costmap_2d:: StaticLayer"}
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}