DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.08
  min_vel_x: -0.08

  max_vel_y: 0.07
  min_vel_y: -0.07

  max_rot_vel: 0.33
  min_rot_vel: -0.33

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.08
  min_vel_trans:  -0.08

  max_vel_theta: 2.0
  min_vel_theta: -2.0

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2 

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false


# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true