global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  transform_tolerance: 0.5
  plugins:
     - {name: static_layer,            type: "rtabmap_ros::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  # rolling_window: true
  # width: 6.0
  # height: 6.0
  # resolution: 0.05
  # map_type: costmap
  