# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_roypy', [dirname(__file__)])
        except ImportError:
            import _roypy
            return _roypy
        if fp is not None:
            try:
                _mod = imp.load_module('_roypy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _roypy = swig_import_helper()
    del swig_import_helper
else:
    import _roypy
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _roypy.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _roypy.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _roypy.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _roypy.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _roypy.SwigPyIterator_equal(self, x)

    def copy(self):
        return _roypy.SwigPyIterator_copy(self)

    def next(self):
        return _roypy.SwigPyIterator_next(self)

    def __next__(self):
        return _roypy.SwigPyIterator___next__(self)

    def previous(self):
        return _roypy.SwigPyIterator_previous(self)

    def advance(self, n):
        return _roypy.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _roypy.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _roypy.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _roypy.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _roypy.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _roypy.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _roypy.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _roypy.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.StringVector___nonzero__(self)

    def __bool__(self):
        return _roypy.StringVector___bool__(self)

    def __len__(self):
        return _roypy.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.StringVector___setitem__(self, *args)

    def pop(self):
        return _roypy.StringVector_pop(self)

    def append(self, x):
        return _roypy.StringVector_append(self, x)

    def empty(self):
        return _roypy.StringVector_empty(self)

    def size(self):
        return _roypy.StringVector_size(self)

    def swap(self, v):
        return _roypy.StringVector_swap(self, v)

    def begin(self):
        return _roypy.StringVector_begin(self)

    def end(self):
        return _roypy.StringVector_end(self)

    def rbegin(self):
        return _roypy.StringVector_rbegin(self)

    def rend(self):
        return _roypy.StringVector_rend(self)

    def clear(self):
        return _roypy.StringVector_clear(self)

    def get_allocator(self):
        return _roypy.StringVector_get_allocator(self)

    def pop_back(self):
        return _roypy.StringVector_pop_back(self)

    def erase(self, *args):
        return _roypy.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_StringVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.StringVector_push_back(self, x)

    def front(self):
        return _roypy.StringVector_front(self)

    def back(self):
        return _roypy.StringVector_back(self)

    def assign(self, n, x):
        return _roypy.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.StringVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.StringVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.StringVector_reserve(self, n)

    def capacity(self):
        return _roypy.StringVector_capacity(self)
    __swig_destroy__ = _roypy.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _roypy.StringVector_swigregister
StringVector_swigregister(StringVector)

class PointVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PointVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.PointVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.PointVector___nonzero__(self)

    def __bool__(self):
        return _roypy.PointVector___bool__(self)

    def __len__(self):
        return _roypy.PointVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.PointVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.PointVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.PointVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.PointVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.PointVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.PointVector___setitem__(self, *args)

    def pop(self):
        return _roypy.PointVector_pop(self)

    def append(self, x):
        return _roypy.PointVector_append(self, x)

    def empty(self):
        return _roypy.PointVector_empty(self)

    def size(self):
        return _roypy.PointVector_size(self)

    def swap(self, v):
        return _roypy.PointVector_swap(self, v)

    def begin(self):
        return _roypy.PointVector_begin(self)

    def end(self):
        return _roypy.PointVector_end(self)

    def rbegin(self):
        return _roypy.PointVector_rbegin(self)

    def rend(self):
        return _roypy.PointVector_rend(self)

    def clear(self):
        return _roypy.PointVector_clear(self)

    def get_allocator(self):
        return _roypy.PointVector_get_allocator(self)

    def pop_back(self):
        return _roypy.PointVector_pop_back(self)

    def erase(self, *args):
        return _roypy.PointVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_PointVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.PointVector_push_back(self, x)

    def front(self):
        return _roypy.PointVector_front(self)

    def back(self):
        return _roypy.PointVector_back(self)

    def assign(self, n, x):
        return _roypy.PointVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.PointVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.PointVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.PointVector_reserve(self, n)

    def capacity(self):
        return _roypy.PointVector_capacity(self)
    __swig_destroy__ = _roypy.delete_PointVector
    __del__ = lambda self: None
PointVector_swigregister = _roypy.PointVector_swigregister
PointVector_swigregister(PointVector)

class InterPointVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, InterPointVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, InterPointVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.InterPointVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.InterPointVector___nonzero__(self)

    def __bool__(self):
        return _roypy.InterPointVector___bool__(self)

    def __len__(self):
        return _roypy.InterPointVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.InterPointVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.InterPointVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.InterPointVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.InterPointVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.InterPointVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.InterPointVector___setitem__(self, *args)

    def pop(self):
        return _roypy.InterPointVector_pop(self)

    def append(self, x):
        return _roypy.InterPointVector_append(self, x)

    def empty(self):
        return _roypy.InterPointVector_empty(self)

    def size(self):
        return _roypy.InterPointVector_size(self)

    def swap(self, v):
        return _roypy.InterPointVector_swap(self, v)

    def begin(self):
        return _roypy.InterPointVector_begin(self)

    def end(self):
        return _roypy.InterPointVector_end(self)

    def rbegin(self):
        return _roypy.InterPointVector_rbegin(self)

    def rend(self):
        return _roypy.InterPointVector_rend(self)

    def clear(self):
        return _roypy.InterPointVector_clear(self)

    def get_allocator(self):
        return _roypy.InterPointVector_get_allocator(self)

    def pop_back(self):
        return _roypy.InterPointVector_pop_back(self)

    def erase(self, *args):
        return _roypy.InterPointVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_InterPointVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.InterPointVector_push_back(self, x)

    def front(self):
        return _roypy.InterPointVector_front(self)

    def back(self):
        return _roypy.InterPointVector_back(self)

    def assign(self, n, x):
        return _roypy.InterPointVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.InterPointVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.InterPointVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.InterPointVector_reserve(self, n)

    def capacity(self):
        return _roypy.InterPointVector_capacity(self)
    __swig_destroy__ = _roypy.delete_InterPointVector
    __del__ = lambda self: None
InterPointVector_swigregister = _roypy.InterPointVector_swigregister
InterPointVector_swigregister(InterPointVector)

class StreamVecVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamVecVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StreamVecVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.StreamVecVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.StreamVecVector___nonzero__(self)

    def __bool__(self):
        return _roypy.StreamVecVector___bool__(self)

    def __len__(self):
        return _roypy.StreamVecVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.StreamVecVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.StreamVecVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.StreamVecVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.StreamVecVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.StreamVecVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.StreamVecVector___setitem__(self, *args)

    def pop(self):
        return _roypy.StreamVecVector_pop(self)

    def append(self, x):
        return _roypy.StreamVecVector_append(self, x)

    def empty(self):
        return _roypy.StreamVecVector_empty(self)

    def size(self):
        return _roypy.StreamVecVector_size(self)

    def swap(self, v):
        return _roypy.StreamVecVector_swap(self, v)

    def begin(self):
        return _roypy.StreamVecVector_begin(self)

    def end(self):
        return _roypy.StreamVecVector_end(self)

    def rbegin(self):
        return _roypy.StreamVecVector_rbegin(self)

    def rend(self):
        return _roypy.StreamVecVector_rend(self)

    def clear(self):
        return _roypy.StreamVecVector_clear(self)

    def get_allocator(self):
        return _roypy.StreamVecVector_get_allocator(self)

    def pop_back(self):
        return _roypy.StreamVecVector_pop_back(self)

    def erase(self, *args):
        return _roypy.StreamVecVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_StreamVecVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.StreamVecVector_push_back(self, x)

    def front(self):
        return _roypy.StreamVecVector_front(self)

    def back(self):
        return _roypy.StreamVecVector_back(self)

    def assign(self, n, x):
        return _roypy.StreamVecVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.StreamVecVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.StreamVecVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.StreamVecVector_reserve(self, n)

    def capacity(self):
        return _roypy.StreamVecVector_capacity(self)
    __swig_destroy__ = _roypy.delete_StreamVecVector
    __del__ = lambda self: None
StreamVecVector_swigregister = _roypy.StreamVecVector_swigregister
StreamVecVector_swigregister(StreamVecVector)

class Uint8VecVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Uint8VecVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Uint8VecVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.Uint8VecVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.Uint8VecVector___nonzero__(self)

    def __bool__(self):
        return _roypy.Uint8VecVector___bool__(self)

    def __len__(self):
        return _roypy.Uint8VecVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.Uint8VecVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.Uint8VecVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.Uint8VecVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.Uint8VecVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.Uint8VecVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.Uint8VecVector___setitem__(self, *args)

    def pop(self):
        return _roypy.Uint8VecVector_pop(self)

    def append(self, x):
        return _roypy.Uint8VecVector_append(self, x)

    def empty(self):
        return _roypy.Uint8VecVector_empty(self)

    def size(self):
        return _roypy.Uint8VecVector_size(self)

    def swap(self, v):
        return _roypy.Uint8VecVector_swap(self, v)

    def begin(self):
        return _roypy.Uint8VecVector_begin(self)

    def end(self):
        return _roypy.Uint8VecVector_end(self)

    def rbegin(self):
        return _roypy.Uint8VecVector_rbegin(self)

    def rend(self):
        return _roypy.Uint8VecVector_rend(self)

    def clear(self):
        return _roypy.Uint8VecVector_clear(self)

    def get_allocator(self):
        return _roypy.Uint8VecVector_get_allocator(self)

    def pop_back(self):
        return _roypy.Uint8VecVector_pop_back(self)

    def erase(self, *args):
        return _roypy.Uint8VecVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_Uint8VecVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.Uint8VecVector_push_back(self, x)

    def front(self):
        return _roypy.Uint8VecVector_front(self)

    def back(self):
        return _roypy.Uint8VecVector_back(self)

    def assign(self, n, x):
        return _roypy.Uint8VecVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.Uint8VecVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.Uint8VecVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.Uint8VecVector_reserve(self, n)

    def capacity(self):
        return _roypy.Uint8VecVector_capacity(self)
    __swig_destroy__ = _roypy.delete_Uint8VecVector
    __del__ = lambda self: None
Uint8VecVector_swigregister = _roypy.Uint8VecVector_swigregister
Uint8VecVector_swigregister(Uint8VecVector)

class Uint32VecVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Uint32VecVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Uint32VecVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.Uint32VecVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.Uint32VecVector___nonzero__(self)

    def __bool__(self):
        return _roypy.Uint32VecVector___bool__(self)

    def __len__(self):
        return _roypy.Uint32VecVector___len__(self)

    def __getslice__(self, i, j):
        return _roypy.Uint32VecVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.Uint32VecVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.Uint32VecVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.Uint32VecVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.Uint32VecVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.Uint32VecVector___setitem__(self, *args)

    def pop(self):
        return _roypy.Uint32VecVector_pop(self)

    def append(self, x):
        return _roypy.Uint32VecVector_append(self, x)

    def empty(self):
        return _roypy.Uint32VecVector_empty(self)

    def size(self):
        return _roypy.Uint32VecVector_size(self)

    def swap(self, v):
        return _roypy.Uint32VecVector_swap(self, v)

    def begin(self):
        return _roypy.Uint32VecVector_begin(self)

    def end(self):
        return _roypy.Uint32VecVector_end(self)

    def rbegin(self):
        return _roypy.Uint32VecVector_rbegin(self)

    def rend(self):
        return _roypy.Uint32VecVector_rend(self)

    def clear(self):
        return _roypy.Uint32VecVector_clear(self)

    def get_allocator(self):
        return _roypy.Uint32VecVector_get_allocator(self)

    def pop_back(self):
        return _roypy.Uint32VecVector_pop_back(self)

    def erase(self, *args):
        return _roypy.Uint32VecVector_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_Uint32VecVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.Uint32VecVector_push_back(self, x)

    def front(self):
        return _roypy.Uint32VecVector_front(self)

    def back(self):
        return _roypy.Uint32VecVector_back(self)

    def assign(self, n, x):
        return _roypy.Uint32VecVector_assign(self, n, x)

    def resize(self, *args):
        return _roypy.Uint32VecVector_resize(self, *args)

    def insert(self, *args):
        return _roypy.Uint32VecVector_insert(self, *args)

    def reserve(self, n):
        return _roypy.Uint32VecVector_reserve(self, n)

    def capacity(self):
        return _roypy.Uint32VecVector_capacity(self)
    __swig_destroy__ = _roypy.delete_Uint32VecVector
    __del__ = lambda self: None
Uint32VecVector_swigregister = _roypy.Uint32VecVector_swigregister
Uint32VecVector_swigregister(Uint32VecVector)


def getVersionString ():
    a,b,c,d = getVersion()
    return str(a)+'.'+str(b)+'.'+str(c)+'.'+str(d)

class ICameraDevicePtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ICameraDevicePtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ICameraDevicePtr, name)
    __repr__ = _swig_repr

    def __deref__(self):
        return _roypy.ICameraDevicePtr___deref__(self)

    def get(self):
        return _roypy.ICameraDevicePtr_get(self)

    def __init__(self):
        this = _roypy.new_ICameraDevicePtr()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_ICameraDevicePtr
    __del__ = lambda self: None

    def initialize(self, *args):
        return _roypy.ICameraDevicePtr_initialize(self, *args)

    def getId(self):
        return _roypy.ICameraDevicePtr_getId(self)

    def getCameraName(self):
        return _roypy.ICameraDevicePtr_getCameraName(self)

    def getCameraInfo(self, *args):
        return _roypy.ICameraDevicePtr_getCameraInfo(self, *args)

    def setUseCase(self, name):
        return _roypy.ICameraDevicePtr_setUseCase(self, name)

    def getUseCases(self):
        return _roypy.ICameraDevicePtr_getUseCases(self)

    def getStreams(self):
        return _roypy.ICameraDevicePtr_getStreams(self)

    def getNumberOfStreams(self, *args):
        return _roypy.ICameraDevicePtr_getNumberOfStreams(self, *args)

    def getCurrentUseCase(self):
        return _roypy.ICameraDevicePtr_getCurrentUseCase(self)

    def setExposureTime(self, *args):
        return _roypy.ICameraDevicePtr_setExposureTime(self, *args)

    def setExposureMode(self, exposureMode, streamId=0):
        return _roypy.ICameraDevicePtr_setExposureMode(self, exposureMode, streamId)

    def getExposureMode(self, streamId=0):
        return _roypy.ICameraDevicePtr_getExposureMode(self, streamId)

    def getExposureLimits(self, *args):
        return _roypy.ICameraDevicePtr_getExposureLimits(self, *args)

    def registerDataListener(self, listener):
        return _roypy.ICameraDevicePtr_registerDataListener(self, listener)

    def unregisterDataListener(self):
        return _roypy.ICameraDevicePtr_unregisterDataListener(self)

    def registerDepthImageListener(self, listener):
        return _roypy.ICameraDevicePtr_registerDepthImageListener(self, listener)

    def unregisterDepthImageListener(self):
        return _roypy.ICameraDevicePtr_unregisterDepthImageListener(self)

    def registerSparsePointCloudListener(self, listener):
        return _roypy.ICameraDevicePtr_registerSparsePointCloudListener(self, listener)

    def unregisterSparsePointCloudListener(self):
        return _roypy.ICameraDevicePtr_unregisterSparsePointCloudListener(self)

    def registerIRImageListener(self, listener):
        return _roypy.ICameraDevicePtr_registerIRImageListener(self, listener)

    def unregisterIRImageListener(self):
        return _roypy.ICameraDevicePtr_unregisterIRImageListener(self)

    def registerDepthIRImageListener(self, listener):
        return _roypy.ICameraDevicePtr_registerDepthIRImageListener(self, listener)

    def unregisterDepthIRImageListener(self):
        return _roypy.ICameraDevicePtr_unregisterDepthIRImageListener(self)

    def registerEventListener(self, listener):
        return _roypy.ICameraDevicePtr_registerEventListener(self, listener)

    def unregisterEventListener(self):
        return _roypy.ICameraDevicePtr_unregisterEventListener(self)

    def startCapture(self):
        return _roypy.ICameraDevicePtr_startCapture(self)

    def stopCapture(self):
        return _roypy.ICameraDevicePtr_stopCapture(self)

    def getMaxSensorWidth(self):
        return _roypy.ICameraDevicePtr_getMaxSensorWidth(self)

    def getMaxSensorHeight(self):
        return _roypy.ICameraDevicePtr_getMaxSensorHeight(self)

    def getLensParameters(self, *args):
        return _roypy.ICameraDevicePtr_getLensParameters(self, *args)

    def isConnected(self):
        return _roypy.ICameraDevicePtr_isConnected(self)

    def isCalibrated(self):
        return _roypy.ICameraDevicePtr_isCalibrated(self)

    def isCapturing(self):
        return _roypy.ICameraDevicePtr_isCapturing(self)

    def getAccessLevel(self):
        return _roypy.ICameraDevicePtr_getAccessLevel(self)

    def startRecording(self, fileName, numberOfFrames=0, frameSkip=0, msSkip=0):
        return _roypy.ICameraDevicePtr_startRecording(self, fileName, numberOfFrames, frameSkip, msSkip)

    def stopRecording(self):
        return _roypy.ICameraDevicePtr_stopRecording(self)

    def registerRecordListener(self, listener):
        return _roypy.ICameraDevicePtr_registerRecordListener(self, listener)

    def unregisterRecordListener(self):
        return _roypy.ICameraDevicePtr_unregisterRecordListener(self)

    def registerExposureListener(self, *args):
        return _roypy.ICameraDevicePtr_registerExposureListener(self, *args)

    def unregisterExposureListener(self):
        return _roypy.ICameraDevicePtr_unregisterExposureListener(self)

    def setFrameRate(self, framerate):
        return _roypy.ICameraDevicePtr_setFrameRate(self, framerate)

    def getFrameRate(self):
        return _roypy.ICameraDevicePtr_getFrameRate(self)

    def getMaxFrameRate(self):
        return _roypy.ICameraDevicePtr_getMaxFrameRate(self)

    def setExternalTrigger(self, useExternalTrigger):
        return _roypy.ICameraDevicePtr_setExternalTrigger(self, useExternalTrigger)

    def setFilterLevel(self, level, streamId=0):
        return _roypy.ICameraDevicePtr_setFilterLevel(self, level, streamId)

    def getFilterLevel(self, streamId=0):
        return _roypy.ICameraDevicePtr_getFilterLevel(self, streamId)

    def getFilterLevels(self, levels, streamId=0):
        return _roypy.ICameraDevicePtr_getFilterLevels(self, levels, streamId)

    def getExposureGroups(self):
        return _roypy.ICameraDevicePtr_getExposureGroups(self)

    def setExposureForGroups(self):
        return _roypy.ICameraDevicePtr_setExposureForGroups(self)

    def setProcessingParameters(self, parameters, streamId=0):
        return _roypy.ICameraDevicePtr_setProcessingParameters(self, parameters, streamId)

    def getProcessingParameters(self, streamId=0):
        return _roypy.ICameraDevicePtr_getProcessingParameters(self, streamId)

    def registerDataListenerExtended(self, listener):
        return _roypy.ICameraDevicePtr_registerDataListenerExtended(self, listener)

    def unregisterDataListenerExtended(self):
        return _roypy.ICameraDevicePtr_unregisterDataListenerExtended(self)

    def setCallbackData(self, *args):
        return _roypy.ICameraDevicePtr_setCallbackData(self, *args)

    def getCalibrationData(self):
        return _roypy.ICameraDevicePtr_getCalibrationData(self)

    def writeCalibrationToFlash(self):
        return _roypy.ICameraDevicePtr_writeCalibrationToFlash(self)

    def setProcessingThreads(self, numThreads, streamId=0):
        return _roypy.ICameraDevicePtr_setProcessingThreads(self, numThreads, streamId)

    def writeDataToFlash(self, *args):
        return _roypy.ICameraDevicePtr_writeDataToFlash(self, *args)

    def setDutyCycle(self, dutyCycle, index):
        return _roypy.ICameraDevicePtr_setDutyCycle(self, dutyCycle, index)

    def shiftLensCenter(self, tx, ty):
        return _roypy.ICameraDevicePtr_shiftLensCenter(self, tx, ty)

    def getLensCenterX(self):
        return _roypy.ICameraDevicePtr_getLensCenterX(self)

    def getLensCenterY(self):
        return _roypy.ICameraDevicePtr_getLensCenterY(self)

    def readRegister(self, registerAddress):
        return _roypy.ICameraDevicePtr_readRegister(self, registerAddress)

    def writeRegister(self, registerAddress, registerValue):
        return _roypy.ICameraDevicePtr_writeRegister(self, registerAddress, registerValue)

    def setExposureTimes(self, exposureTimes):
        return _roypy.ICameraDevicePtr_setExposureTimes(self, exposureTimes)

    def asReplay(self):
        return _roypy.ICameraDevicePtr_asReplay(self)

    def setCalibrationDataFromFile(self, filename):
        return _roypy.ICameraDevicePtr_setCalibrationDataFromFile(self, filename)

    def setCalibrationDataFromBuffer(self, data):
        return _roypy.ICameraDevicePtr_setCalibrationDataFromBuffer(self, data)
ICameraDevicePtr_swigregister = _roypy.ICameraDevicePtr_swigregister
ICameraDevicePtr_swigregister(ICameraDevicePtr)

class LensParamMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LensParamMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LensParamMap, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.LensParamMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.LensParamMap___nonzero__(self)

    def __bool__(self):
        return _roypy.LensParamMap___bool__(self)

    def __len__(self):
        return _roypy.LensParamMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _roypy.LensParamMap___getitem__(self, key)

    def __delitem__(self, key):
        return _roypy.LensParamMap___delitem__(self, key)

    def has_key(self, key):
        return _roypy.LensParamMap_has_key(self, key)

    def keys(self):
        return _roypy.LensParamMap_keys(self)

    def values(self):
        return _roypy.LensParamMap_values(self)

    def items(self):
        return _roypy.LensParamMap_items(self)

    def __contains__(self, key):
        return _roypy.LensParamMap___contains__(self, key)

    def key_iterator(self):
        return _roypy.LensParamMap_key_iterator(self)

    def value_iterator(self):
        return _roypy.LensParamMap_value_iterator(self)

    def __setitem__(self, *args):
        return _roypy.LensParamMap___setitem__(self, *args)

    def asdict(self):
        return _roypy.LensParamMap_asdict(self)

    def __init__(self, *args):
        this = _roypy.new_LensParamMap(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def empty(self):
        return _roypy.LensParamMap_empty(self)

    def size(self):
        return _roypy.LensParamMap_size(self)

    def swap(self, v):
        return _roypy.LensParamMap_swap(self, v)

    def begin(self):
        return _roypy.LensParamMap_begin(self)

    def end(self):
        return _roypy.LensParamMap_end(self)

    def rbegin(self):
        return _roypy.LensParamMap_rbegin(self)

    def rend(self):
        return _roypy.LensParamMap_rend(self)

    def clear(self):
        return _roypy.LensParamMap_clear(self)

    def get_allocator(self):
        return _roypy.LensParamMap_get_allocator(self)

    def count(self, x):
        return _roypy.LensParamMap_count(self, x)

    def erase(self, *args):
        return _roypy.LensParamMap_erase(self, *args)

    def find(self, x):
        return _roypy.LensParamMap_find(self, x)

    def lower_bound(self, x):
        return _roypy.LensParamMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _roypy.LensParamMap_upper_bound(self, x)
    __swig_destroy__ = _roypy.delete_LensParamMap
    __del__ = lambda self: None
LensParamMap_swigregister = _roypy.LensParamMap_swigregister
LensParamMap_swigregister(LensParamMap)

class CamInfoMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CamInfoMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CamInfoMap, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _roypy.CamInfoMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _roypy.CamInfoMap___nonzero__(self)

    def __bool__(self):
        return _roypy.CamInfoMap___bool__(self)

    def __len__(self):
        return _roypy.CamInfoMap___len__(self)

    def __getslice__(self, i, j):
        return _roypy.CamInfoMap___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _roypy.CamInfoMap___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _roypy.CamInfoMap___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _roypy.CamInfoMap___delitem__(self, *args)

    def __getitem__(self, *args):
        return _roypy.CamInfoMap___getitem__(self, *args)

    def __setitem__(self, *args):
        return _roypy.CamInfoMap___setitem__(self, *args)

    def pop(self):
        return _roypy.CamInfoMap_pop(self)

    def append(self, x):
        return _roypy.CamInfoMap_append(self, x)

    def empty(self):
        return _roypy.CamInfoMap_empty(self)

    def size(self):
        return _roypy.CamInfoMap_size(self)

    def swap(self, v):
        return _roypy.CamInfoMap_swap(self, v)

    def begin(self):
        return _roypy.CamInfoMap_begin(self)

    def end(self):
        return _roypy.CamInfoMap_end(self)

    def rbegin(self):
        return _roypy.CamInfoMap_rbegin(self)

    def rend(self):
        return _roypy.CamInfoMap_rend(self)

    def clear(self):
        return _roypy.CamInfoMap_clear(self)

    def get_allocator(self):
        return _roypy.CamInfoMap_get_allocator(self)

    def pop_back(self):
        return _roypy.CamInfoMap_pop_back(self)

    def erase(self, *args):
        return _roypy.CamInfoMap_erase(self, *args)

    def __init__(self, *args):
        this = _roypy.new_CamInfoMap(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _roypy.CamInfoMap_push_back(self, x)

    def front(self):
        return _roypy.CamInfoMap_front(self)

    def back(self):
        return _roypy.CamInfoMap_back(self)

    def assign(self, n, x):
        return _roypy.CamInfoMap_assign(self, n, x)

    def resize(self, *args):
        return _roypy.CamInfoMap_resize(self, *args)

    def insert(self, *args):
        return _roypy.CamInfoMap_insert(self, *args)

    def reserve(self, n):
        return _roypy.CamInfoMap_reserve(self, n)

    def capacity(self):
        return _roypy.CamInfoMap_capacity(self)
    __swig_destroy__ = _roypy.delete_CamInfoMap
    __del__ = lambda self: None
CamInfoMap_swigregister = _roypy.CamInfoMap_swigregister
CamInfoMap_swigregister(CamInfoMap)

class exposurePair(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, exposurePair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, exposurePair, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _roypy.new_exposurePair(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["first"] = _roypy.exposurePair_first_set
    __swig_getmethods__["first"] = _roypy.exposurePair_first_get
    if _newclass:
        first = _swig_property(_roypy.exposurePair_first_get, _roypy.exposurePair_first_set)
    __swig_setmethods__["second"] = _roypy.exposurePair_second_set
    __swig_getmethods__["second"] = _roypy.exposurePair_second_get
    if _newclass:
        second = _swig_property(_roypy.exposurePair_second_get, _roypy.exposurePair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _roypy.delete_exposurePair
    __del__ = lambda self: None
exposurePair_swigregister = _roypy.exposurePair_swigregister
exposurePair_swigregister(exposurePair)


def getLensCenter (self):
    x = self.getLensCenterX ()
    y = self.getLensCenterY ()
    return x,y

ICameraDevicePtr.getLensCenter = getLensCenter


def getVersion():
    return _roypy.getVersion()
getVersion = _roypy.getVersion

def getErrorString(status):
    return _roypy.getErrorString(status)
getErrorString = _roypy.getErrorString
class CameraManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CameraManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CameraManager, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _roypy.new_CameraManager(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_CameraManager
    __del__ = lambda self: None
    __swig_getmethods__["getAccessLevel"] = lambda x: _roypy.CameraManager_getAccessLevel
    if _newclass:
        getAccessLevel = staticmethod(_roypy.CameraManager_getAccessLevel)

    def getConnectedCameraList(self):
        return _roypy.CameraManager_getConnectedCameraList(self)

    def createCamera(self, *args):
        return _roypy.CameraManager_createCamera(self, *args)

    def getConnectedCameraNames(self):
        return _roypy.CameraManager_getConnectedCameraNames(self)

    def registerEventListener(self, listener):
        return _roypy.CameraManager_registerEventListener(self, listener)

    def unregisterEventListener(self):
        return _roypy.CameraManager_unregisterEventListener(self)

    def setCacheFolder(self, path):
        return _roypy.CameraManager_setCacheFolder(self, path)
CameraManager_swigregister = _roypy.CameraManager_swigregister
CameraManager_swigregister(CameraManager)

def CameraManager_getAccessLevel(*args):
    return _roypy.CameraManager_getAccessLevel(*args)
CameraManager_getAccessLevel = _roypy.CameraManager_getAccessLevel

class ICameraDevice(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ICameraDevice, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ICameraDevice, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_ICameraDevice
    __del__ = lambda self: None

    def initialize(self, *args):
        return _roypy.ICameraDevice_initialize(self, *args)

    def getId(self):
        return _roypy.ICameraDevice_getId(self)

    def getCameraName(self):
        return _roypy.ICameraDevice_getCameraName(self)

    def setUseCase(self, name):
        return _roypy.ICameraDevice_setUseCase(self, name)

    def getUseCases(self):
        return _roypy.ICameraDevice_getUseCases(self)

    def getStreams(self):
        return _roypy.ICameraDevice_getStreams(self)

    def getCurrentUseCase(self):
        return _roypy.ICameraDevice_getCurrentUseCase(self)

    def setExposureMode(self, exposureMode, streamId=0):
        return _roypy.ICameraDevice_setExposureMode(self, exposureMode, streamId)

    def getExposureMode(self, streamId=0):
        return _roypy.ICameraDevice_getExposureMode(self, streamId)

    def registerDataListener(self, listener):
        return _roypy.ICameraDevice_registerDataListener(self, listener)

    def unregisterDataListener(self):
        return _roypy.ICameraDevice_unregisterDataListener(self)

    def registerDepthImageListener(self, listener):
        return _roypy.ICameraDevice_registerDepthImageListener(self, listener)

    def unregisterDepthImageListener(self):
        return _roypy.ICameraDevice_unregisterDepthImageListener(self)

    def registerSparsePointCloudListener(self, listener):
        return _roypy.ICameraDevice_registerSparsePointCloudListener(self, listener)

    def unregisterSparsePointCloudListener(self):
        return _roypy.ICameraDevice_unregisterSparsePointCloudListener(self)

    def registerIRImageListener(self, listener):
        return _roypy.ICameraDevice_registerIRImageListener(self, listener)

    def unregisterIRImageListener(self):
        return _roypy.ICameraDevice_unregisterIRImageListener(self)

    def registerDepthIRImageListener(self, listener):
        return _roypy.ICameraDevice_registerDepthIRImageListener(self, listener)

    def unregisterDepthIRImageListener(self):
        return _roypy.ICameraDevice_unregisterDepthIRImageListener(self)

    def registerEventListener(self, listener):
        return _roypy.ICameraDevice_registerEventListener(self, listener)

    def unregisterEventListener(self):
        return _roypy.ICameraDevice_unregisterEventListener(self)

    def startCapture(self):
        return _roypy.ICameraDevice_startCapture(self)

    def stopCapture(self):
        return _roypy.ICameraDevice_stopCapture(self)

    def getMaxSensorWidth(self):
        return _roypy.ICameraDevice_getMaxSensorWidth(self)

    def getMaxSensorHeight(self):
        return _roypy.ICameraDevice_getMaxSensorHeight(self)

    def isConnected(self):
        return _roypy.ICameraDevice_isConnected(self)

    def isCalibrated(self):
        return _roypy.ICameraDevice_isCalibrated(self)

    def isCapturing(self):
        return _roypy.ICameraDevice_isCapturing(self)

    def getAccessLevel(self):
        return _roypy.ICameraDevice_getAccessLevel(self)

    def startRecording(self, fileName, numberOfFrames=0, frameSkip=0, msSkip=0):
        return _roypy.ICameraDevice_startRecording(self, fileName, numberOfFrames, frameSkip, msSkip)

    def stopRecording(self):
        return _roypy.ICameraDevice_stopRecording(self)

    def registerRecordListener(self, listener):
        return _roypy.ICameraDevice_registerRecordListener(self, listener)

    def unregisterRecordListener(self):
        return _roypy.ICameraDevice_unregisterRecordListener(self)

    def registerExposureListener(self, *args):
        return _roypy.ICameraDevice_registerExposureListener(self, *args)

    def unregisterExposureListener(self):
        return _roypy.ICameraDevice_unregisterExposureListener(self)

    def setFrameRate(self, framerate):
        return _roypy.ICameraDevice_setFrameRate(self, framerate)

    def getFrameRate(self):
        return _roypy.ICameraDevice_getFrameRate(self)

    def getMaxFrameRate(self):
        return _roypy.ICameraDevice_getMaxFrameRate(self)

    def setExternalTrigger(self, useExternalTrigger):
        return _roypy.ICameraDevice_setExternalTrigger(self, useExternalTrigger)

    def setFilterLevel(self, level, streamId=0):
        return _roypy.ICameraDevice_setFilterLevel(self, level, streamId)

    def getFilterLevel(self, streamId=0):
        return _roypy.ICameraDevice_getFilterLevel(self, streamId)

    def getFilterLevels(self, levels, streamId=0):
        return _roypy.ICameraDevice_getFilterLevels(self, levels, streamId)

    def getExposureGroups(self):
        return _roypy.ICameraDevice_getExposureGroups(self)

    def setExposureTime(self, *args):
        return _roypy.ICameraDevice_setExposureTime(self, *args)

    def setExposureForGroups(self):
        return _roypy.ICameraDevice_setExposureForGroups(self)

    def setProcessingParameters(self, parameters, streamId=0):
        return _roypy.ICameraDevice_setProcessingParameters(self, parameters, streamId)

    def getProcessingParameters(self, streamId=0):
        return _roypy.ICameraDevice_getProcessingParameters(self, streamId)

    def registerDataListenerExtended(self, listener):
        return _roypy.ICameraDevice_registerDataListenerExtended(self, listener)

    def unregisterDataListenerExtended(self):
        return _roypy.ICameraDevice_unregisterDataListenerExtended(self)

    def setCallbackData(self, *args):
        return _roypy.ICameraDevice_setCallbackData(self, *args)

    def getCalibrationData(self):
        return _roypy.ICameraDevice_getCalibrationData(self)

    def writeCalibrationToFlash(self):
        return _roypy.ICameraDevice_writeCalibrationToFlash(self)

    def setProcessingThreads(self, numThreads, streamId=0):
        return _roypy.ICameraDevice_setProcessingThreads(self, numThreads, streamId)

    def writeDataToFlash(self, *args):
        return _roypy.ICameraDevice_writeDataToFlash(self, *args)

    def setDutyCycle(self, dutyCycle, index):
        return _roypy.ICameraDevice_setDutyCycle(self, dutyCycle, index)

    def shiftLensCenter(self, tx, ty):
        return _roypy.ICameraDevice_shiftLensCenter(self, tx, ty)

    def getLensParameters(self, *args):
        return _roypy.ICameraDevice_getLensParameters(self, *args)

    def getCameraInfo(self, *args):
        return _roypy.ICameraDevice_getCameraInfo(self, *args)

    def getNumberOfStreams(self, *args):
        return _roypy.ICameraDevice_getNumberOfStreams(self, *args)

    def getExposureLimits(self, *args):
        return _roypy.ICameraDevice_getExposureLimits(self, *args)

    def getLensCenterX(self):
        return _roypy.ICameraDevice_getLensCenterX(self)

    def getLensCenterY(self):
        return _roypy.ICameraDevice_getLensCenterY(self)

    def readRegister(self, registerAddress):
        return _roypy.ICameraDevice_readRegister(self, registerAddress)

    def writeRegister(self, registerAddress, registerValue):
        return _roypy.ICameraDevice_writeRegister(self, registerAddress, registerValue)

    def setExposureTimes(self, exposureTimes):
        return _roypy.ICameraDevice_setExposureTimes(self, exposureTimes)

    def asReplay(self):
        return _roypy.ICameraDevice_asReplay(self)

    def setCalibrationDataFromFile(self, filename):
        return _roypy.ICameraDevice_setCalibrationDataFromFile(self, filename)

    def setCalibrationDataFromBuffer(self, data):
        return _roypy.ICameraDevice_setCalibrationDataFromBuffer(self, data)
ICameraDevice_swigregister = _roypy.ICameraDevice_swigregister
ICameraDevice_swigregister(ICameraDevice)


_roypy.CameraStatus_SUCCESS_swigconstant(_roypy)
CameraStatus_SUCCESS = _roypy.CameraStatus_SUCCESS

_roypy.CameraStatus_RUNTIME_ERROR_swigconstant(_roypy)
CameraStatus_RUNTIME_ERROR = _roypy.CameraStatus_RUNTIME_ERROR

_roypy.CameraStatus_DISCONNECTED_swigconstant(_roypy)
CameraStatus_DISCONNECTED = _roypy.CameraStatus_DISCONNECTED

_roypy.CameraStatus_INVALID_VALUE_swigconstant(_roypy)
CameraStatus_INVALID_VALUE = _roypy.CameraStatus_INVALID_VALUE

_roypy.CameraStatus_TIMEOUT_swigconstant(_roypy)
CameraStatus_TIMEOUT = _roypy.CameraStatus_TIMEOUT

_roypy.CameraStatus_LOGIC_ERROR_swigconstant(_roypy)
CameraStatus_LOGIC_ERROR = _roypy.CameraStatus_LOGIC_ERROR

_roypy.CameraStatus_NOT_IMPLEMENTED_swigconstant(_roypy)
CameraStatus_NOT_IMPLEMENTED = _roypy.CameraStatus_NOT_IMPLEMENTED

_roypy.CameraStatus_OUT_OF_BOUNDS_swigconstant(_roypy)
CameraStatus_OUT_OF_BOUNDS = _roypy.CameraStatus_OUT_OF_BOUNDS

_roypy.CameraStatus_RESOURCE_ERROR_swigconstant(_roypy)
CameraStatus_RESOURCE_ERROR = _roypy.CameraStatus_RESOURCE_ERROR

_roypy.CameraStatus_FILE_NOT_FOUND_swigconstant(_roypy)
CameraStatus_FILE_NOT_FOUND = _roypy.CameraStatus_FILE_NOT_FOUND

_roypy.CameraStatus_COULD_NOT_OPEN_swigconstant(_roypy)
CameraStatus_COULD_NOT_OPEN = _roypy.CameraStatus_COULD_NOT_OPEN

_roypy.CameraStatus_DATA_NOT_FOUND_swigconstant(_roypy)
CameraStatus_DATA_NOT_FOUND = _roypy.CameraStatus_DATA_NOT_FOUND

_roypy.CameraStatus_DEVICE_IS_BUSY_swigconstant(_roypy)
CameraStatus_DEVICE_IS_BUSY = _roypy.CameraStatus_DEVICE_IS_BUSY

_roypy.CameraStatus_WRONG_DATA_FORMAT_FOUND_swigconstant(_roypy)
CameraStatus_WRONG_DATA_FORMAT_FOUND = _roypy.CameraStatus_WRONG_DATA_FORMAT_FOUND

_roypy.CameraStatus_USECASE_NOT_SUPPORTED_swigconstant(_roypy)
CameraStatus_USECASE_NOT_SUPPORTED = _roypy.CameraStatus_USECASE_NOT_SUPPORTED

_roypy.CameraStatus_FRAMERATE_NOT_SUPPORTED_swigconstant(_roypy)
CameraStatus_FRAMERATE_NOT_SUPPORTED = _roypy.CameraStatus_FRAMERATE_NOT_SUPPORTED

_roypy.CameraStatus_EXPOSURE_TIME_NOT_SUPPORTED_swigconstant(_roypy)
CameraStatus_EXPOSURE_TIME_NOT_SUPPORTED = _roypy.CameraStatus_EXPOSURE_TIME_NOT_SUPPORTED

_roypy.CameraStatus_DEVICE_NOT_INITIALIZED_swigconstant(_roypy)
CameraStatus_DEVICE_NOT_INITIALIZED = _roypy.CameraStatus_DEVICE_NOT_INITIALIZED

_roypy.CameraStatus_CALIBRATION_DATA_ERROR_swigconstant(_roypy)
CameraStatus_CALIBRATION_DATA_ERROR = _roypy.CameraStatus_CALIBRATION_DATA_ERROR

_roypy.CameraStatus_INSUFFICIENT_PRIVILEGES_swigconstant(_roypy)
CameraStatus_INSUFFICIENT_PRIVILEGES = _roypy.CameraStatus_INSUFFICIENT_PRIVILEGES

_roypy.CameraStatus_DEVICE_ALREADY_INITIALIZED_swigconstant(_roypy)
CameraStatus_DEVICE_ALREADY_INITIALIZED = _roypy.CameraStatus_DEVICE_ALREADY_INITIALIZED

_roypy.CameraStatus_EXPOSURE_MODE_INVALID_swigconstant(_roypy)
CameraStatus_EXPOSURE_MODE_INVALID = _roypy.CameraStatus_EXPOSURE_MODE_INVALID

_roypy.CameraStatus_NO_CALIBRATION_DATA_swigconstant(_roypy)
CameraStatus_NO_CALIBRATION_DATA = _roypy.CameraStatus_NO_CALIBRATION_DATA

_roypy.CameraStatus_INSUFFICIENT_BANDWIDTH_swigconstant(_roypy)
CameraStatus_INSUFFICIENT_BANDWIDTH = _roypy.CameraStatus_INSUFFICIENT_BANDWIDTH

_roypy.CameraStatus_DUTYCYCLE_NOT_SUPPORTED_swigconstant(_roypy)
CameraStatus_DUTYCYCLE_NOT_SUPPORTED = _roypy.CameraStatus_DUTYCYCLE_NOT_SUPPORTED

_roypy.CameraStatus_SPECTRE_NOT_INITIALIZED_swigconstant(_roypy)
CameraStatus_SPECTRE_NOT_INITIALIZED = _roypy.CameraStatus_SPECTRE_NOT_INITIALIZED

_roypy.CameraStatus_NO_USE_CASES_swigconstant(_roypy)
CameraStatus_NO_USE_CASES = _roypy.CameraStatus_NO_USE_CASES

_roypy.CameraStatus_NO_USE_CASES_FOR_LEVEL_swigconstant(_roypy)
CameraStatus_NO_USE_CASES_FOR_LEVEL = _roypy.CameraStatus_NO_USE_CASES_FOR_LEVEL

_roypy.CameraStatus_FSM_INVALID_TRANSITION_swigconstant(_roypy)
CameraStatus_FSM_INVALID_TRANSITION = _roypy.CameraStatus_FSM_INVALID_TRANSITION

_roypy.CameraStatus_UNKNOWN_swigconstant(_roypy)
CameraStatus_UNKNOWN = _roypy.CameraStatus_UNKNOWN

def getStatusString(status):
    return _roypy.getStatusString(status)
getStatusString = _roypy.getStatusString

def __lshift__(os, status):
    return _roypy.__lshift__(os, status)
__lshift__ = _roypy.__lshift__

_roypy.CameraAccessLevel_L1_swigconstant(_roypy)
CameraAccessLevel_L1 = _roypy.CameraAccessLevel_L1

_roypy.CameraAccessLevel_L2_swigconstant(_roypy)
CameraAccessLevel_L2 = _roypy.CameraAccessLevel_L2

_roypy.CameraAccessLevel_L3_swigconstant(_roypy)
CameraAccessLevel_L3 = _roypy.CameraAccessLevel_L3

_roypy.CameraAccessLevel_L4_swigconstant(_roypy)
CameraAccessLevel_L4 = _roypy.CameraAccessLevel_L4
class IDepthDataListener(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IDepthDataListener, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IDepthDataListener, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IDepthDataListener
    __del__ = lambda self: None

    def onNewData(self, data):
        return _roypy.IDepthDataListener_onNewData(self, data)

    def __init__(self):
        if self.__class__ == IDepthDataListener:
            _self = None
        else:
            _self = self
        this = _roypy.new_IDepthDataListener(_self, )
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _roypy.disown_IDepthDataListener(self)
        return weakref_proxy(self)
IDepthDataListener_swigregister = _roypy.IDepthDataListener_swigregister
IDepthDataListener_swigregister(IDepthDataListener)

class IDepthImageListener(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IDepthImageListener, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IDepthImageListener, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IDepthImageListener
    __del__ = lambda self: None

    def onNewData(self, data):
        return _roypy.IDepthImageListener_onNewData(self, data)

    def __init__(self):
        if self.__class__ == IDepthImageListener:
            _self = None
        else:
            _self = self
        this = _roypy.new_IDepthImageListener(_self, )
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _roypy.disown_IDepthImageListener(self)
        return weakref_proxy(self)
IDepthImageListener_swigregister = _roypy.IDepthImageListener_swigregister
IDepthImageListener_swigregister(IDepthImageListener)

class IExtendedData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IExtendedData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IExtendedData, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IExtendedData
    __del__ = lambda self: None

    def hasDepthData(self):
        return _roypy.IExtendedData_hasDepthData(self)

    def hasRawData(self):
        return _roypy.IExtendedData_hasRawData(self)

    def hasIntermediateData(self):
        return _roypy.IExtendedData_hasIntermediateData(self)

    def getRawData(self):
        return _roypy.IExtendedData_getRawData(self)

    def getDepthData(self):
        return _roypy.IExtendedData_getDepthData(self)

    def getIntermediateData(self):
        return _roypy.IExtendedData_getIntermediateData(self)
IExtendedData_swigregister = _roypy.IExtendedData_swigregister
IExtendedData_swigregister(IExtendedData)

class RawData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RawData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RawData, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _roypy.new_RawData(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["timeStamp"] = _roypy.RawData_timeStamp_set
    __swig_getmethods__["timeStamp"] = _roypy.RawData_timeStamp_get
    if _newclass:
        timeStamp = _swig_property(_roypy.RawData_timeStamp_get, _roypy.RawData_timeStamp_set)
    __swig_setmethods__["streamId"] = _roypy.RawData_streamId_set
    __swig_getmethods__["streamId"] = _roypy.RawData_streamId_get
    if _newclass:
        streamId = _swig_property(_roypy.RawData_streamId_get, _roypy.RawData_streamId_set)
    __swig_setmethods__["width"] = _roypy.RawData_width_set
    __swig_getmethods__["width"] = _roypy.RawData_width_get
    if _newclass:
        width = _swig_property(_roypy.RawData_width_get, _roypy.RawData_width_set)
    __swig_setmethods__["height"] = _roypy.RawData_height_set
    __swig_getmethods__["height"] = _roypy.RawData_height_get
    if _newclass:
        height = _swig_property(_roypy.RawData_height_get, _roypy.RawData_height_set)
    __swig_setmethods__["exposureGroupNames"] = _roypy.RawData_exposureGroupNames_set
    __swig_getmethods__["exposureGroupNames"] = _roypy.RawData_exposureGroupNames_get
    if _newclass:
        exposureGroupNames = _swig_property(_roypy.RawData_exposureGroupNames_get, _roypy.RawData_exposureGroupNames_set)
    __swig_setmethods__["rawFrameCount"] = _roypy.RawData_rawFrameCount_set
    __swig_getmethods__["rawFrameCount"] = _roypy.RawData_rawFrameCount_get
    if _newclass:
        rawFrameCount = _swig_property(_roypy.RawData_rawFrameCount_get, _roypy.RawData_rawFrameCount_set)
    __swig_setmethods__["modulationFrequencies"] = _roypy.RawData_modulationFrequencies_set
    __swig_getmethods__["modulationFrequencies"] = _roypy.RawData_modulationFrequencies_get
    if _newclass:
        modulationFrequencies = _swig_property(_roypy.RawData_modulationFrequencies_get, _roypy.RawData_modulationFrequencies_set)
    __swig_setmethods__["exposureTimes"] = _roypy.RawData_exposureTimes_set
    __swig_getmethods__["exposureTimes"] = _roypy.RawData_exposureTimes_get
    if _newclass:
        exposureTimes = _swig_property(_roypy.RawData_exposureTimes_get, _roypy.RawData_exposureTimes_set)
    __swig_setmethods__["illuminationTemperature"] = _roypy.RawData_illuminationTemperature_set
    __swig_getmethods__["illuminationTemperature"] = _roypy.RawData_illuminationTemperature_get
    if _newclass:
        illuminationTemperature = _swig_property(_roypy.RawData_illuminationTemperature_get, _roypy.RawData_illuminationTemperature_set)
    __swig_setmethods__["phaseAngles"] = _roypy.RawData_phaseAngles_set
    __swig_getmethods__["phaseAngles"] = _roypy.RawData_phaseAngles_get
    if _newclass:
        phaseAngles = _swig_property(_roypy.RawData_phaseAngles_get, _roypy.RawData_phaseAngles_set)
    __swig_setmethods__["illuminationEnabled"] = _roypy.RawData_illuminationEnabled_set
    __swig_getmethods__["illuminationEnabled"] = _roypy.RawData_illuminationEnabled_get
    if _newclass:
        illuminationEnabled = _swig_property(_roypy.RawData_illuminationEnabled_get, _roypy.RawData_illuminationEnabled_set)

    def getRawPhase(self, idx):
        return _roypy.RawData_getRawPhase(self, idx)
    __swig_destroy__ = _roypy.delete_RawData
    __del__ = lambda self: None
RawData_swigregister = _roypy.RawData_swigregister
RawData_swigregister(RawData)


_roypy.CallbackData__None_swigconstant(_roypy)
CallbackData__None = _roypy.CallbackData__None

_roypy.CallbackData_Raw_swigconstant(_roypy)
CallbackData_Raw = _roypy.CallbackData_Raw

_roypy.CallbackData_Depth_swigconstant(_roypy)
CallbackData_Depth = _roypy.CallbackData_Depth

_roypy.CallbackData_Intermediate_swigconstant(_roypy)
CallbackData_Intermediate = _roypy.CallbackData_Intermediate
class IntermediatePoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntermediatePoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntermediatePoint, name)
    __repr__ = _swig_repr
    __swig_setmethods__["distance"] = _roypy.IntermediatePoint_distance_set
    __swig_getmethods__["distance"] = _roypy.IntermediatePoint_distance_get
    if _newclass:
        distance = _swig_property(_roypy.IntermediatePoint_distance_get, _roypy.IntermediatePoint_distance_set)
    __swig_setmethods__["amplitude"] = _roypy.IntermediatePoint_amplitude_set
    __swig_getmethods__["amplitude"] = _roypy.IntermediatePoint_amplitude_get
    if _newclass:
        amplitude = _swig_property(_roypy.IntermediatePoint_amplitude_get, _roypy.IntermediatePoint_amplitude_set)
    __swig_setmethods__["intensity"] = _roypy.IntermediatePoint_intensity_set
    __swig_getmethods__["intensity"] = _roypy.IntermediatePoint_intensity_get
    if _newclass:
        intensity = _swig_property(_roypy.IntermediatePoint_intensity_get, _roypy.IntermediatePoint_intensity_set)
    __swig_setmethods__["flags"] = _roypy.IntermediatePoint_flags_set
    __swig_getmethods__["flags"] = _roypy.IntermediatePoint_flags_get
    if _newclass:
        flags = _swig_property(_roypy.IntermediatePoint_flags_get, _roypy.IntermediatePoint_flags_set)

    def __init__(self):
        this = _roypy.new_IntermediatePoint()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_IntermediatePoint
    __del__ = lambda self: None
IntermediatePoint_swigregister = _roypy.IntermediatePoint_swigregister
IntermediatePoint_swigregister(IntermediatePoint)

class IntermediateData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntermediateData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntermediateData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version"] = _roypy.IntermediateData_version_set
    __swig_getmethods__["version"] = _roypy.IntermediateData_version_get
    if _newclass:
        version = _swig_property(_roypy.IntermediateData_version_get, _roypy.IntermediateData_version_set)
    __swig_setmethods__["timeStamp"] = _roypy.IntermediateData_timeStamp_set
    __swig_getmethods__["timeStamp"] = _roypy.IntermediateData_timeStamp_get
    if _newclass:
        timeStamp = _swig_property(_roypy.IntermediateData_timeStamp_get, _roypy.IntermediateData_timeStamp_set)
    __swig_setmethods__["streamId"] = _roypy.IntermediateData_streamId_set
    __swig_getmethods__["streamId"] = _roypy.IntermediateData_streamId_get
    if _newclass:
        streamId = _swig_property(_roypy.IntermediateData_streamId_get, _roypy.IntermediateData_streamId_set)
    __swig_setmethods__["width"] = _roypy.IntermediateData_width_set
    __swig_getmethods__["width"] = _roypy.IntermediateData_width_get
    if _newclass:
        width = _swig_property(_roypy.IntermediateData_width_get, _roypy.IntermediateData_width_set)
    __swig_setmethods__["height"] = _roypy.IntermediateData_height_set
    __swig_getmethods__["height"] = _roypy.IntermediateData_height_get
    if _newclass:
        height = _swig_property(_roypy.IntermediateData_height_get, _roypy.IntermediateData_height_set)
    __swig_setmethods__["modulationFrequencies"] = _roypy.IntermediateData_modulationFrequencies_set
    __swig_getmethods__["modulationFrequencies"] = _roypy.IntermediateData_modulationFrequencies_get
    if _newclass:
        modulationFrequencies = _swig_property(_roypy.IntermediateData_modulationFrequencies_get, _roypy.IntermediateData_modulationFrequencies_set)
    __swig_setmethods__["exposureTimes"] = _roypy.IntermediateData_exposureTimes_set
    __swig_getmethods__["exposureTimes"] = _roypy.IntermediateData_exposureTimes_get
    if _newclass:
        exposureTimes = _swig_property(_roypy.IntermediateData_exposureTimes_get, _roypy.IntermediateData_exposureTimes_set)
    __swig_setmethods__["numFrequencies"] = _roypy.IntermediateData_numFrequencies_set
    __swig_getmethods__["numFrequencies"] = _roypy.IntermediateData_numFrequencies_get
    if _newclass:
        numFrequencies = _swig_property(_roypy.IntermediateData_numFrequencies_get, _roypy.IntermediateData_numFrequencies_set)
    __swig_setmethods__["processingParameters"] = _roypy.IntermediateData_processingParameters_set
    __swig_getmethods__["processingParameters"] = _roypy.IntermediateData_processingParameters_get
    if _newclass:
        processingParameters = _swig_property(_roypy.IntermediateData_processingParameters_get, _roypy.IntermediateData_processingParameters_set)

    def points(self):
        return _roypy.IntermediateData_points(self)

    def getDistance(self, idx):
        return _roypy.IntermediateData_getDistance(self, idx)

    def getAmplitude(self, idx):
        return _roypy.IntermediateData_getAmplitude(self, idx)

    def getIntensity(self, idx):
        return _roypy.IntermediateData_getIntensity(self, idx)

    def getFlags(self, idx):
        return _roypy.IntermediateData_getFlags(self, idx)

    def getNumPoints(self):
        return _roypy.IntermediateData_getNumPoints(self)

    def __init__(self):
        this = _roypy.new_IntermediateData()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_IntermediateData
    __del__ = lambda self: None
IntermediateData_swigregister = _roypy.IntermediateData_swigregister
IntermediateData_swigregister(IntermediateData)

class IExtendedDataListener(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IExtendedDataListener, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IExtendedDataListener, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IExtendedDataListener
    __del__ = lambda self: None

    def onNewData(self, data):
        return _roypy.IExtendedDataListener_onNewData(self, data)

    def __init__(self):
        if self.__class__ == IExtendedDataListener:
            _self = None
        else:
            _self = self
        this = _roypy.new_IExtendedDataListener(_self, )
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _roypy.disown_IExtendedDataListener(self)
        return weakref_proxy(self)
IExtendedDataListener_swigregister = _roypy.IExtendedDataListener_swigregister
IExtendedDataListener_swigregister(IExtendedDataListener)

class IRecordStopListener(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IRecordStopListener, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IRecordStopListener, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IRecordStopListener
    __del__ = lambda self: None

    def onRecordingStopped(self, numFrames):
        return _roypy.IRecordStopListener_onRecordingStopped(self, numFrames)

    def __init__(self):
        if self.__class__ == IRecordStopListener:
            _self = None
        else:
            _self = self
        this = _roypy.new_IRecordStopListener(_self, )
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _roypy.disown_IRecordStopListener(self)
        return weakref_proxy(self)
IRecordStopListener_swigregister = _roypy.IRecordStopListener_swigregister
IRecordStopListener_swigregister(IRecordStopListener)

class DepthPoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DepthPoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DepthPoint, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _roypy.DepthPoint_x_set
    __swig_getmethods__["x"] = _roypy.DepthPoint_x_get
    if _newclass:
        x = _swig_property(_roypy.DepthPoint_x_get, _roypy.DepthPoint_x_set)
    __swig_setmethods__["y"] = _roypy.DepthPoint_y_set
    __swig_getmethods__["y"] = _roypy.DepthPoint_y_get
    if _newclass:
        y = _swig_property(_roypy.DepthPoint_y_get, _roypy.DepthPoint_y_set)
    __swig_setmethods__["z"] = _roypy.DepthPoint_z_set
    __swig_getmethods__["z"] = _roypy.DepthPoint_z_get
    if _newclass:
        z = _swig_property(_roypy.DepthPoint_z_get, _roypy.DepthPoint_z_set)
    __swig_setmethods__["noise"] = _roypy.DepthPoint_noise_set
    __swig_getmethods__["noise"] = _roypy.DepthPoint_noise_get
    if _newclass:
        noise = _swig_property(_roypy.DepthPoint_noise_get, _roypy.DepthPoint_noise_set)
    __swig_setmethods__["grayValue"] = _roypy.DepthPoint_grayValue_set
    __swig_getmethods__["grayValue"] = _roypy.DepthPoint_grayValue_get
    if _newclass:
        grayValue = _swig_property(_roypy.DepthPoint_grayValue_get, _roypy.DepthPoint_grayValue_set)
    __swig_setmethods__["depthConfidence"] = _roypy.DepthPoint_depthConfidence_set
    __swig_getmethods__["depthConfidence"] = _roypy.DepthPoint_depthConfidence_get
    if _newclass:
        depthConfidence = _swig_property(_roypy.DepthPoint_depthConfidence_get, _roypy.DepthPoint_depthConfidence_set)

    def __init__(self):
        this = _roypy.new_DepthPoint()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_DepthPoint
    __del__ = lambda self: None
DepthPoint_swigregister = _roypy.DepthPoint_swigregister
DepthPoint_swigregister(DepthPoint)

class DepthData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DepthData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DepthData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version"] = _roypy.DepthData_version_set
    __swig_getmethods__["version"] = _roypy.DepthData_version_get
    if _newclass:
        version = _swig_property(_roypy.DepthData_version_get, _roypy.DepthData_version_set)
    __swig_setmethods__["timeStamp"] = _roypy.DepthData_timeStamp_set
    __swig_getmethods__["timeStamp"] = _roypy.DepthData_timeStamp_get
    if _newclass:
        timeStamp = _swig_property(_roypy.DepthData_timeStamp_get, _roypy.DepthData_timeStamp_set)
    __swig_setmethods__["streamId"] = _roypy.DepthData_streamId_set
    __swig_getmethods__["streamId"] = _roypy.DepthData_streamId_get
    if _newclass:
        streamId = _swig_property(_roypy.DepthData_streamId_get, _roypy.DepthData_streamId_set)
    __swig_setmethods__["width"] = _roypy.DepthData_width_set
    __swig_getmethods__["width"] = _roypy.DepthData_width_get
    if _newclass:
        width = _swig_property(_roypy.DepthData_width_get, _roypy.DepthData_width_set)
    __swig_setmethods__["height"] = _roypy.DepthData_height_set
    __swig_getmethods__["height"] = _roypy.DepthData_height_get
    if _newclass:
        height = _swig_property(_roypy.DepthData_height_get, _roypy.DepthData_height_set)
    __swig_setmethods__["exposureTimes"] = _roypy.DepthData_exposureTimes_set
    __swig_getmethods__["exposureTimes"] = _roypy.DepthData_exposureTimes_get
    if _newclass:
        exposureTimes = _swig_property(_roypy.DepthData_exposureTimes_get, _roypy.DepthData_exposureTimes_set)
    __swig_setmethods__["hasDepth"] = _roypy.DepthData_hasDepth_set
    __swig_getmethods__["hasDepth"] = _roypy.DepthData_hasDepth_get
    if _newclass:
        hasDepth = _swig_property(_roypy.DepthData_hasDepth_get, _roypy.DepthData_hasDepth_set)

    def points(self):
        return _roypy.DepthData_points(self)

    def fastPoints(self, p):
        return _roypy.DepthData_fastPoints(self, p)

    def npoints (self):
        return self.fastPoints(self.width * self.height * 6).reshape(-1,self.width,6)


    def getX(self, idx):
        return _roypy.DepthData_getX(self, idx)

    def getY(self, idx):
        return _roypy.DepthData_getY(self, idx)

    def getZ(self, idx):
        return _roypy.DepthData_getZ(self, idx)

    def getNoise(self, idx):
        return _roypy.DepthData_getNoise(self, idx)

    def getGrayValue(self, idx):
        return _roypy.DepthData_getGrayValue(self, idx)

    def getDepthConfidence(self, idx):
        return _roypy.DepthData_getDepthConfidence(self, idx)

    def getNumPoints(self):
        return _roypy.DepthData_getNumPoints(self)

    def __init__(self):
        this = _roypy.new_DepthData()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_DepthData
    __del__ = lambda self: None
DepthData_swigregister = _roypy.DepthData_swigregister
DepthData_swigregister(DepthData)

class DepthImage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DepthImage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DepthImage, name)
    __repr__ = _swig_repr
    __swig_setmethods__["timestamp"] = _roypy.DepthImage_timestamp_set
    __swig_getmethods__["timestamp"] = _roypy.DepthImage_timestamp_get
    if _newclass:
        timestamp = _swig_property(_roypy.DepthImage_timestamp_get, _roypy.DepthImage_timestamp_set)
    __swig_setmethods__["streamId"] = _roypy.DepthImage_streamId_set
    __swig_getmethods__["streamId"] = _roypy.DepthImage_streamId_get
    if _newclass:
        streamId = _swig_property(_roypy.DepthImage_streamId_get, _roypy.DepthImage_streamId_set)
    __swig_setmethods__["width"] = _roypy.DepthImage_width_set
    __swig_getmethods__["width"] = _roypy.DepthImage_width_get
    if _newclass:
        width = _swig_property(_roypy.DepthImage_width_get, _roypy.DepthImage_width_set)
    __swig_setmethods__["height"] = _roypy.DepthImage_height_set
    __swig_getmethods__["height"] = _roypy.DepthImage_height_get
    if _newclass:
        height = _swig_property(_roypy.DepthImage_height_get, _roypy.DepthImage_height_set)

    def cdData(self):
        return _roypy.DepthImage_cdData(self)

    def getCDData(self, idx):
        return _roypy.DepthImage_getCDData(self, idx)

    def getNumPoints(self):
        return _roypy.DepthImage_getNumPoints(self)

    def __init__(self):
        this = _roypy.new_DepthImage()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_DepthImage
    __del__ = lambda self: None
DepthImage_swigregister = _roypy.DepthImage_swigregister
DepthImage_swigregister(DepthImage)


_roypy.ProcessingFlag_ConsistencyTolerance_Float_swigconstant(_roypy)
ProcessingFlag_ConsistencyTolerance_Float = _roypy.ProcessingFlag_ConsistencyTolerance_Float

_roypy.ProcessingFlag_FlyingPixelsF0_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelsF0_Float = _roypy.ProcessingFlag_FlyingPixelsF0_Float

_roypy.ProcessingFlag_FlyingPixelsF1_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelsF1_Float = _roypy.ProcessingFlag_FlyingPixelsF1_Float

_roypy.ProcessingFlag_FlyingPixelsFarDist_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelsFarDist_Float = _roypy.ProcessingFlag_FlyingPixelsFarDist_Float

_roypy.ProcessingFlag_FlyingPixelsNearDist_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelsNearDist_Float = _roypy.ProcessingFlag_FlyingPixelsNearDist_Float

_roypy.ProcessingFlag_LowerSaturationThreshold_Int_swigconstant(_roypy)
ProcessingFlag_LowerSaturationThreshold_Int = _roypy.ProcessingFlag_LowerSaturationThreshold_Int

_roypy.ProcessingFlag_UpperSaturationThreshold_Int_swigconstant(_roypy)
ProcessingFlag_UpperSaturationThreshold_Int = _roypy.ProcessingFlag_UpperSaturationThreshold_Int

_roypy.ProcessingFlag_MPIAmpThreshold_Float_swigconstant(_roypy)
ProcessingFlag_MPIAmpThreshold_Float = _roypy.ProcessingFlag_MPIAmpThreshold_Float

_roypy.ProcessingFlag_MPIDistThreshold_Float_swigconstant(_roypy)
ProcessingFlag_MPIDistThreshold_Float = _roypy.ProcessingFlag_MPIDistThreshold_Float

_roypy.ProcessingFlag_MPINoiseDistance_Float_swigconstant(_roypy)
ProcessingFlag_MPINoiseDistance_Float = _roypy.ProcessingFlag_MPINoiseDistance_Float

_roypy.ProcessingFlag_NoiseThreshold_Float_swigconstant(_roypy)
ProcessingFlag_NoiseThreshold_Float = _roypy.ProcessingFlag_NoiseThreshold_Float

_roypy.ProcessingFlag_AdaptiveNoiseFilterType_Int_swigconstant(_roypy)
ProcessingFlag_AdaptiveNoiseFilterType_Int = _roypy.ProcessingFlag_AdaptiveNoiseFilterType_Int

_roypy.ProcessingFlag_AutoExposureRefAmplitude_Float_swigconstant(_roypy)
ProcessingFlag_AutoExposureRefAmplitude_Float = _roypy.ProcessingFlag_AutoExposureRefAmplitude_Float

_roypy.ProcessingFlag_UseAdaptiveNoiseFilter_Bool_swigconstant(_roypy)
ProcessingFlag_UseAdaptiveNoiseFilter_Bool = _roypy.ProcessingFlag_UseAdaptiveNoiseFilter_Bool

_roypy.ProcessingFlag_UseAutoExposure_Bool_swigconstant(_roypy)
ProcessingFlag_UseAutoExposure_Bool = _roypy.ProcessingFlag_UseAutoExposure_Bool

_roypy.ProcessingFlag_UseRemoveFlyingPixel_Bool_swigconstant(_roypy)
ProcessingFlag_UseRemoveFlyingPixel_Bool = _roypy.ProcessingFlag_UseRemoveFlyingPixel_Bool

_roypy.ProcessingFlag_UseMPIFlagAverage_Bool_swigconstant(_roypy)
ProcessingFlag_UseMPIFlagAverage_Bool = _roypy.ProcessingFlag_UseMPIFlagAverage_Bool

_roypy.ProcessingFlag_UseMPIFlag_Amp_Bool_swigconstant(_roypy)
ProcessingFlag_UseMPIFlag_Amp_Bool = _roypy.ProcessingFlag_UseMPIFlag_Amp_Bool

_roypy.ProcessingFlag_UseMPIFlag_Dist_Bool_swigconstant(_roypy)
ProcessingFlag_UseMPIFlag_Dist_Bool = _roypy.ProcessingFlag_UseMPIFlag_Dist_Bool

_roypy.ProcessingFlag_UseValidateImage_Bool_swigconstant(_roypy)
ProcessingFlag_UseValidateImage_Bool = _roypy.ProcessingFlag_UseValidateImage_Bool

_roypy.ProcessingFlag_UseRemoveStrayLight_Bool_swigconstant(_roypy)
ProcessingFlag_UseRemoveStrayLight_Bool = _roypy.ProcessingFlag_UseRemoveStrayLight_Bool

_roypy.ProcessingFlag_UseSparsePointCloud_Bool_swigconstant(_roypy)
ProcessingFlag_UseSparsePointCloud_Bool = _roypy.ProcessingFlag_UseSparsePointCloud_Bool

_roypy.ProcessingFlag_UseFilter2Freq_Bool_swigconstant(_roypy)
ProcessingFlag_UseFilter2Freq_Bool = _roypy.ProcessingFlag_UseFilter2Freq_Bool

_roypy.ProcessingFlag_GlobalBinning_Int_swigconstant(_roypy)
ProcessingFlag_GlobalBinning_Int = _roypy.ProcessingFlag_GlobalBinning_Int

_roypy.ProcessingFlag_UseAdaptiveBinning_Bool_swigconstant(_roypy)
ProcessingFlag_UseAdaptiveBinning_Bool = _roypy.ProcessingFlag_UseAdaptiveBinning_Bool

_roypy.ProcessingFlag_AutoExposureRefValue_Float_swigconstant(_roypy)
ProcessingFlag_AutoExposureRefValue_Float = _roypy.ProcessingFlag_AutoExposureRefValue_Float

_roypy.ProcessingFlag_UseSmoothingFilter_Bool_swigconstant(_roypy)
ProcessingFlag_UseSmoothingFilter_Bool = _roypy.ProcessingFlag_UseSmoothingFilter_Bool

_roypy.ProcessingFlag_SmoothingAlpha_Float_swigconstant(_roypy)
ProcessingFlag_SmoothingAlpha_Float = _roypy.ProcessingFlag_SmoothingAlpha_Float

_roypy.ProcessingFlag_SmoothingFilterType_Int_swigconstant(_roypy)
ProcessingFlag_SmoothingFilterType_Int = _roypy.ProcessingFlag_SmoothingFilterType_Int

_roypy.ProcessingFlag_UseFlagSBI_Bool_swigconstant(_roypy)
ProcessingFlag_UseFlagSBI_Bool = _roypy.ProcessingFlag_UseFlagSBI_Bool

_roypy.ProcessingFlag_UseHoleFilling_Bool_swigconstant(_roypy)
ProcessingFlag_UseHoleFilling_Bool = _roypy.ProcessingFlag_UseHoleFilling_Bool

_roypy.ProcessingFlag_Reserved1_swigconstant(_roypy)
ProcessingFlag_Reserved1 = _roypy.ProcessingFlag_Reserved1

_roypy.ProcessingFlag_Reserved2_swigconstant(_roypy)
ProcessingFlag_Reserved2 = _roypy.ProcessingFlag_Reserved2

_roypy.ProcessingFlag_Reserved3_swigconstant(_roypy)
ProcessingFlag_Reserved3 = _roypy.ProcessingFlag_Reserved3

_roypy.ProcessingFlag_Reserved4_swigconstant(_roypy)
ProcessingFlag_Reserved4 = _roypy.ProcessingFlag_Reserved4

_roypy.ProcessingFlag_Reserved5_swigconstant(_roypy)
ProcessingFlag_Reserved5 = _roypy.ProcessingFlag_Reserved5

_roypy.ProcessingFlag_Reserved6_swigconstant(_roypy)
ProcessingFlag_Reserved6 = _roypy.ProcessingFlag_Reserved6

_roypy.ProcessingFlag_Reserved7_swigconstant(_roypy)
ProcessingFlag_Reserved7 = _roypy.ProcessingFlag_Reserved7

_roypy.ProcessingFlag_Reserved8_swigconstant(_roypy)
ProcessingFlag_Reserved8 = _roypy.ProcessingFlag_Reserved8

_roypy.ProcessingFlag_AutoExpoMin_Int_swigconstant(_roypy)
ProcessingFlag_AutoExpoMin_Int = _roypy.ProcessingFlag_AutoExpoMin_Int

_roypy.ProcessingFlag_AutoExpoMax_Int_swigconstant(_roypy)
ProcessingFlag_AutoExpoMax_Int = _roypy.ProcessingFlag_AutoExpoMax_Int

_roypy.ProcessingFlag_SpectreProcessingType_Int_swigconstant(_roypy)
ProcessingFlag_SpectreProcessingType_Int = _roypy.ProcessingFlag_SpectreProcessingType_Int

_roypy.ProcessingFlag_UseGrayImageFallbackAmplitude_Bool_swigconstant(_roypy)
ProcessingFlag_UseGrayImageFallbackAmplitude_Bool = _roypy.ProcessingFlag_UseGrayImageFallbackAmplitude_Bool

_roypy.ProcessingFlag_GrayImageMeanMap_Int_swigconstant(_roypy)
ProcessingFlag_GrayImageMeanMap_Int = _roypy.ProcessingFlag_GrayImageMeanMap_Int

_roypy.ProcessingFlag_NoiseFilterSigmaD_Float_swigconstant(_roypy)
ProcessingFlag_NoiseFilterSigmaD_Float = _roypy.ProcessingFlag_NoiseFilterSigmaD_Float

_roypy.ProcessingFlag_NoiseFilterIterations_Int_swigconstant(_roypy)
ProcessingFlag_NoiseFilterIterations_Int = _roypy.ProcessingFlag_NoiseFilterIterations_Int

_roypy.ProcessingFlag_FlyingPixelAngleLimit_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelAngleLimit_Float = _roypy.ProcessingFlag_FlyingPixelAngleLimit_Float

_roypy.ProcessingFlag_FlyingPixelAmpThreshold_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelAmpThreshold_Float = _roypy.ProcessingFlag_FlyingPixelAmpThreshold_Float

_roypy.ProcessingFlag_FlyingPixelMinNeighbors_Int_swigconstant(_roypy)
ProcessingFlag_FlyingPixelMinNeighbors_Int = _roypy.ProcessingFlag_FlyingPixelMinNeighbors_Int

_roypy.ProcessingFlag_FlyingPixelMaxNeighbors_Int_swigconstant(_roypy)
ProcessingFlag_FlyingPixelMaxNeighbors_Int = _roypy.ProcessingFlag_FlyingPixelMaxNeighbors_Int

_roypy.ProcessingFlag_FlyingPixelNoiseRatioThresh_Float_swigconstant(_roypy)
ProcessingFlag_FlyingPixelNoiseRatioThresh_Float = _roypy.ProcessingFlag_FlyingPixelNoiseRatioThresh_Float

_roypy.ProcessingFlag_SmoothingFilterResetThreshold_Float_swigconstant(_roypy)
ProcessingFlag_SmoothingFilterResetThreshold_Float = _roypy.ProcessingFlag_SmoothingFilterResetThreshold_Float

_roypy.ProcessingFlag_CCThresh_Int_swigconstant(_roypy)
ProcessingFlag_CCThresh_Int = _roypy.ProcessingFlag_CCThresh_Int

_roypy.ProcessingFlag_PhaseNoiseThresh_Float_swigconstant(_roypy)
ProcessingFlag_PhaseNoiseThresh_Float = _roypy.ProcessingFlag_PhaseNoiseThresh_Float

_roypy.ProcessingFlag_StraylightThreshold_Float_swigconstant(_roypy)
ProcessingFlag_StraylightThreshold_Float = _roypy.ProcessingFlag_StraylightThreshold_Float

_roypy.ProcessingFlag_NoiseFilterSigmaA_Float_swigconstant(_roypy)
ProcessingFlag_NoiseFilterSigmaA_Float = _roypy.ProcessingFlag_NoiseFilterSigmaA_Float

_roypy.ProcessingFlag_TwoFreqCombinationType_Int_swigconstant(_roypy)
ProcessingFlag_TwoFreqCombinationType_Int = _roypy.ProcessingFlag_TwoFreqCombinationType_Int

_roypy.ProcessingFlag_UseCorrectMPI_Bool_swigconstant(_roypy)
ProcessingFlag_UseCorrectMPI_Bool = _roypy.ProcessingFlag_UseCorrectMPI_Bool

_roypy.ProcessingFlag_NUM_FLAGS_swigconstant(_roypy)
ProcessingFlag_NUM_FLAGS = _roypy.ProcessingFlag_NUM_FLAGS

def getProcessingFlagName(mode):
    return _roypy.getProcessingFlagName(mode)
getProcessingFlagName = _roypy.getProcessingFlagName

def parseProcessingFlagName(modeName, processingFlag):
    return _roypy.parseProcessingFlagName(modeName, processingFlag)
parseProcessingFlagName = _roypy.parseProcessingFlagName

_roypy.ExposureMode_MANUAL_swigconstant(_roypy)
ExposureMode_MANUAL = _roypy.ExposureMode_MANUAL

_roypy.ExposureMode_AUTOMATIC_swigconstant(_roypy)
ExposureMode_AUTOMATIC = _roypy.ExposureMode_AUTOMATIC

_roypy.FilterLevel_Off_swigconstant(_roypy)
FilterLevel_Off = _roypy.FilterLevel_Off

_roypy.FilterLevel_Deprecated1_swigconstant(_roypy)
FilterLevel_Deprecated1 = _roypy.FilterLevel_Deprecated1

_roypy.FilterLevel_Deprecated2_swigconstant(_roypy)
FilterLevel_Deprecated2 = _roypy.FilterLevel_Deprecated2

_roypy.FilterLevel_Deprecated3_swigconstant(_roypy)
FilterLevel_Deprecated3 = _roypy.FilterLevel_Deprecated3

_roypy.FilterLevel_Deprecated4_swigconstant(_roypy)
FilterLevel_Deprecated4 = _roypy.FilterLevel_Deprecated4

_roypy.FilterLevel_IR1_swigconstant(_roypy)
FilterLevel_IR1 = _roypy.FilterLevel_IR1

_roypy.FilterLevel_IR2_swigconstant(_roypy)
FilterLevel_IR2 = _roypy.FilterLevel_IR2

_roypy.FilterLevel_AF1_swigconstant(_roypy)
FilterLevel_AF1 = _roypy.FilterLevel_AF1

_roypy.FilterLevel_CM1_swigconstant(_roypy)
FilterLevel_CM1 = _roypy.FilterLevel_CM1

_roypy.FilterLevel_Binning_1_Basic_swigconstant(_roypy)
FilterLevel_Binning_1_Basic = _roypy.FilterLevel_Binning_1_Basic

_roypy.FilterLevel_Binning_2_Basic_swigconstant(_roypy)
FilterLevel_Binning_2_Basic = _roypy.FilterLevel_Binning_2_Basic

_roypy.FilterLevel_Binning_3_Basic_swigconstant(_roypy)
FilterLevel_Binning_3_Basic = _roypy.FilterLevel_Binning_3_Basic

_roypy.FilterLevel_Binning_4_Basic_swigconstant(_roypy)
FilterLevel_Binning_4_Basic = _roypy.FilterLevel_Binning_4_Basic

_roypy.FilterLevel_Binning_8_Basic_swigconstant(_roypy)
FilterLevel_Binning_8_Basic = _roypy.FilterLevel_Binning_8_Basic

_roypy.FilterLevel_Binning_10_Basic_swigconstant(_roypy)
FilterLevel_Binning_10_Basic = _roypy.FilterLevel_Binning_10_Basic

_roypy.FilterLevel_Binning_1_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_1_Efficiency = _roypy.FilterLevel_Binning_1_Efficiency

_roypy.FilterLevel_Binning_2_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_2_Efficiency = _roypy.FilterLevel_Binning_2_Efficiency

_roypy.FilterLevel_Binning_3_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_3_Efficiency = _roypy.FilterLevel_Binning_3_Efficiency

_roypy.FilterLevel_Binning_4_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_4_Efficiency = _roypy.FilterLevel_Binning_4_Efficiency

_roypy.FilterLevel_Binning_8_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_8_Efficiency = _roypy.FilterLevel_Binning_8_Efficiency

_roypy.FilterLevel_Binning_10_Efficiency_swigconstant(_roypy)
FilterLevel_Binning_10_Efficiency = _roypy.FilterLevel_Binning_10_Efficiency

_roypy.FilterLevel_Legacy_swigconstant(_roypy)
FilterLevel_Legacy = _roypy.FilterLevel_Legacy

_roypy.FilterLevel_Full_swigconstant(_roypy)
FilterLevel_Full = _roypy.FilterLevel_Full

_roypy.FilterLevel_Custom_swigconstant(_roypy)
FilterLevel_Custom = _roypy.FilterLevel_Custom

def getFilterLevelName(level):
    return _roypy.getFilterLevelName(level)
getFilterLevelName = _roypy.getFilterLevelName

def getFilterLevelFromName(name):
    return _roypy.getFilterLevelFromName(name)
getFilterLevelFromName = _roypy.getFilterLevelFromName
class LensParameters(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LensParameters, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LensParameters, name)
    __repr__ = _swig_repr
    __swig_setmethods__["principalPoint"] = _roypy.LensParameters_principalPoint_set
    __swig_getmethods__["principalPoint"] = _roypy.LensParameters_principalPoint_get
    if _newclass:
        principalPoint = _swig_property(_roypy.LensParameters_principalPoint_get, _roypy.LensParameters_principalPoint_set)
    __swig_setmethods__["focalLength"] = _roypy.LensParameters_focalLength_set
    __swig_getmethods__["focalLength"] = _roypy.LensParameters_focalLength_get
    if _newclass:
        focalLength = _swig_property(_roypy.LensParameters_focalLength_get, _roypy.LensParameters_focalLength_set)
    __swig_setmethods__["distortionTangential"] = _roypy.LensParameters_distortionTangential_set
    __swig_getmethods__["distortionTangential"] = _roypy.LensParameters_distortionTangential_get
    if _newclass:
        distortionTangential = _swig_property(_roypy.LensParameters_distortionTangential_get, _roypy.LensParameters_distortionTangential_set)
    __swig_setmethods__["distortionRadial"] = _roypy.LensParameters_distortionRadial_set
    __swig_getmethods__["distortionRadial"] = _roypy.LensParameters_distortionRadial_get
    if _newclass:
        distortionRadial = _swig_property(_roypy.LensParameters_distortionRadial_get, _roypy.LensParameters_distortionRadial_set)

    def __init__(self):
        this = _roypy.new_LensParameters()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _roypy.delete_LensParameters
    __del__ = lambda self: None
LensParameters_swigregister = _roypy.LensParameters_swigregister
LensParameters_swigregister(LensParameters)

class IReplay(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IReplay, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IReplay, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _roypy.delete_IReplay
    __del__ = lambda self: None

    def seek(self, frameNumber):
        return _roypy.IReplay_seek(self, frameNumber)

    def loop(self, restart):
        return _roypy.IReplay_loop(self, restart)

    def useTimestamps(self, timestampsUsed):
        return _roypy.IReplay_useTimestamps(self, timestampsUsed)

    def frameCount(self):
        return _roypy.IReplay_frameCount(self)

    def currentFrame(self):
        return _roypy.IReplay_currentFrame(self)

    def pause(self):
        return _roypy.IReplay_pause(self)

    def resume(self):
        return _roypy.IReplay_resume(self)

    def registerStopListener(self, listener):
        return _roypy.IReplay_registerStopListener(self, listener)

    def unregisterStopListener(self):
        return _roypy.IReplay_unregisterStopListener(self)

    def getFileVersion(self):
        return _roypy.IReplay_getFileVersion(self)

    def getMajorVersion(self):
        return _roypy.IReplay_getMajorVersion(self)

    def getMinorVersion(self):
        return _roypy.IReplay_getMinorVersion(self)

    def getPatchVersion(self):
        return _roypy.IReplay_getPatchVersion(self)

    def getBuildVersion(self):
        return _roypy.IReplay_getBuildVersion(self)

    def setPlaybackRange(self, first, last):
        return _roypy.IReplay_setPlaybackRange(self, first, last)

    def getPlaybackRange(self, first, last):
        return _roypy.IReplay_getPlaybackRange(self, first, last)
IReplay_swigregister = _roypy.IReplay_swigregister
IReplay_swigregister(IReplay)

# This file is compatible with both classic and new-style classes.


