controller_list:
  - name: fake_front_left_controller
    joints:
      - m11
      - m12
      - m13
  - name: fake_front_right_controller
    joints:
      - m21
      - m22
      - m23
  - name: fake_middle_left_controller
    joints:
      - m31
      - m32
      - m33
  - name: fake_middle_right_controller
    joints:
      - m41
      - m42
      - m43
  - name: fake_back_left_controller
    joints:
      - m51
      - m52
      - m53
  - name: fake_back_right_controller
    joints:
      - m61
      - m62
      - m63